server:
  port: 8004
spring:
  application:
    name: cloud-consul-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.31.47:3306/orchard?useUnicode=true&characterEncoding=utf-8&useSSL=false
    password: liujinshan
    username: root
  cloud:
    consul:
      host: localhost
      post: 8500
      discovery:
        register: true
        service-name: ${spring.application.name}

mybatis:
  #MyBatis相关自定义配置
  #configLocation: classpath:mybatis.xml
  #实体类所做包
  type-aliases-package: com.atguigu.springcloud.entities
  #mapper.xml所在位置
  mapperLocations: classpath:mapper/*.xml

