server:
  port: 80
spring:
  application:
    name: cloud-consul-consumer
  cloud:
    consul:
      host: localhost
      post: 8500
      discovery:
        register: true
        service-name: ${spring.application.name}
